### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by villa101101** [kernel1983/SWEN-3000-Assigment-1#2]
There is an internal error when the suggested link in the readme file is searched for after starting the server.

**Comment by kernel1983** [comment]
Can you provide me the internal error detail?
The information in the console

**Comment by villa101101** [comment]
![Screen Shot 2019-04-29 at 12 28 22 PM](https://user-images.githubusercontent.com/34188824/56876531-a3e8ad00-6a7a-11e9-9a1a-bdcfe3194243.png)

**Comment by villa101101** [comment]
![Screen Shot 2019-04-29 at 12 28 22 PM](https://user-images.githubusercontent.com/34188824/56876585-0477ea00-6a7b-11e9-9720-993828f20cca.png)
